services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
  api:
    build: api
    command: npm start
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
  client:
    build: client
    command: npm start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 3000:3000
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080